CREATE TABLE IF NOT EXISTS public.agents (
  id text PRIMARY KEY,
  aircall_user_id bigint UNIQUE,
  name text NOT NULL,
  team text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.calls (
  id text PRIMARY KEY,
  aircall_id text UNIQUE NOT NULL,
  started_at timestamptz,
  direction text,
  duration_s integer,
  scope text,
  ivr_branch text,
  answered boolean,
  transferred boolean NOT NULL DEFAULT false,
  agent_id text REFERENCES public.agents(id),
  raw jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.transcripts (
  call_id text PRIMARY KEY REFERENCES public.calls(id) ON DELETE CASCADE,
  language text,
  text text,
  diarization jsonb NOT NULL DEFAULT '[]'::jsonb,
  source text,
  fetched_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.evaluations (
  id text PRIMARY KEY,
  call_id text UNIQUE REFERENCES public.calls(id) ON DELETE CASCADE,
  model_name text,
  model_version text,
  rubric_version text,
  score_global numeric(3,1),
  duration_ms integer,
  tokens_in integer,
  tokens_out integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  raw jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.soft_skills (
  evaluation_id text REFERENCES public.evaluations(id) ON DELETE CASCADE,
  criterion text NOT NULL,
  score numeric(3,1),
  weight numeric(3,2),
  citation text,
  PRIMARY KEY (evaluation_id, criterion)
);

CREATE TABLE IF NOT EXISTS public.issues (
  id text PRIMARY KEY,
  evaluation_id text REFERENCES public.evaluations(id) ON DELETE CASCADE,
  type text,
  severity text,
  description text,
  citation text,
  kb_reference text
);

CREATE TABLE IF NOT EXISTS public.kb_gaps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  detected_on date NOT NULL,
  topic text NOT NULL,
  frequency integer NOT NULL DEFAULT 0,
  example_call_ids text[] NOT NULL DEFAULT '{}',
  status text NOT NULL DEFAULT 'new'
);

CREATE TABLE IF NOT EXISTS public.daily_kpi_snapshot (
  date date NOT NULL,
  scope text NOT NULL,
  total_calls integer,
  pickup_rate numeric(5,1),
  abandon_rate numeric(5,1),
  avg_handle_time integer,
  repeat_caller_rate numeric(5,1),
  avg_soft_score numeric(4,1),
  coverage_pct numeric(5,1),
  computed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (date, scope)
);

CREATE TABLE IF NOT EXISTS public.llm_runs (
  id text PRIMARY KEY,
  started_at timestamptz NOT NULL,
  ended_at timestamptz,
  mode text,
  model text,
  calls_count integer,
  errors_count integer,
  tokens_total integer,
  status text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_calls_started_at ON public.calls(started_at);
CREATE INDEX IF NOT EXISTS idx_calls_agent_id ON public.calls(agent_id);
CREATE INDEX IF NOT EXISTS idx_evaluations_created_at ON public.evaluations(created_at);
CREATE INDEX IF NOT EXISTS idx_issues_evaluation_id ON public.issues(evaluation_id);
CREATE INDEX IF NOT EXISTS idx_kb_gaps_detected_on ON public.kb_gaps(detected_on);
