-- 022_kb_suggestions.sql
-- Persiste les suggestions KB (missing / incomplete / to_revise) générées par
-- analysis_pipeline pour le post Slack quotidien. Avant cette migration ces
-- suggestions ne vivaient que dans le message Slack et étaient perdues.
--
-- Source : analysis["kb_gaps"] dict (cf. _build_fallback_kb_gaps).
-- Lue par : cockpit /qa/kb-gaps.

create table if not exists public.kb_suggestions (
  id            bigint generated by default as identity primary key,
  detected_on   date not null,
  section       text not null check (section in ('missing', 'incomplete', 'to_revise')),
  title         text not null,
  description   text,
  source_label  text,
  source_count  integer,
  status        text not null default 'new'
    check (status in ('new', 'in_progress', 'done', 'dismissed')),
  assignee      text,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  updated_by    text,
  unique (detected_on, section, title)
);

create index if not exists idx_kb_suggestions_detected_on
  on public.kb_suggestions(detected_on desc);
create index if not exists idx_kb_suggestions_status
  on public.kb_suggestions(status) where status <> 'done';

create or replace function public.touch_kb_suggestions()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists trg_kb_suggestions_touch on public.kb_suggestions;
create trigger trg_kb_suggestions_touch
  before update on public.kb_suggestions
  for each row execute function public.touch_kb_suggestions();

-- Vue : dernières suggestions actives (pour le cockpit).
create or replace view public.v_kb_suggestions_active as
  select
    s.*,
    case when s.detected_on >= current_date - 7 then true else false end as is_recent
  from public.kb_suggestions s
  where s.status in ('new', 'in_progress')
  order by s.detected_on desc, s.section, s.id desc;

comment on table public.kb_suggestions is
  'Suggestions KB générées par analysis_pipeline (sections missing/incomplete/to_revise du post Slack quotidien).';
